[package]
name = "mpca-pm"
version = "0.1.0"
edition = "2024"

[dependencies]
minijinja = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
